const resArray = [
  {
    id: "23688",
    name: "McDonald's",
    cloudinaryImageId: "bb7ae131544c7d37e10fc5faf76f09d6",
    locality: "Marathahalli",
    areaName: "Brookefield",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
    avgRating: 4.3,
    parentId: "630",
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 22,
      lastMileTravel: 2.6,
      serviceability: "SERVICEABLE",
      slaString: "22 mins",
      lastMileTravelString: "2.6 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "272268",
    name: "EatFit",
    cloudinaryImageId: "6126c9b45de2cb222405c1af8a321e74",
    locality: "Varthur Main Road",
    areaName: "Whitefield",
    costForTwo: "₹270 for two",
    cuisines: [
      "Chinese",
      "Healthy Food",
      "Tandoor",
      "Pizzas",
      "North Indian",
      "Thalis",
      "Biryani",
    ],
    avgRating: 4.2,
    parentId: "76139",
    avgRatingString: "4.2",
    totalRatingsString: "5K+",
    sla: {
      deliveryTime: 23,
      lastMileTravel: 2.9,
      serviceability: "SERVICEABLE",
      slaString: "23 mins",
      lastMileTravelString: "2.9 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "444077",
    name: "Magnolia Bakery",
    cloudinaryImageId: "6f0945b8b18d9f4241dd1cd9a70e23d7",
    locality: "Phoenix Market City",
    areaName: "Mahadevpura",
    costForTwo: "₹500 for two",
    cuisines: ["Bakery", "Desserts", "Ice Cream"],
    avgRating: 4.5,
    parentId: "267303",
    avgRatingString: "4.5",
    totalRatingsString: "1K+",
    sla: {
      deliveryTime: 35,
      lastMileTravel: 7.9,
      serviceability: "SERVICEABLE",
      slaString: "35 mins",
      lastMileTravelString: "7.9 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "289268",
    name: "BOX8 - Desi Meals",
    cloudinaryImageId: "69a061b7e0f951cef2b4947946f94ec6",
    locality: "Kundalahalli",
    areaName: "Marathahalli",
    costForTwo: "₹250 for two",
    cuisines: ["North Indian", "Biryani", "Thalis", "Home Food"],
    avgRating: 4.3,
    parentId: "10655",
    avgRatingString: "4.3",
    totalRatingsString: "1K+",
    sla: {
      deliveryTime: 14,
      lastMileTravel: 2.2,
      serviceability: "SERVICEABLE",
      slaString: "9-19 mins",
      lastMileTravelString: "2.2 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "156411",
    name: "The Good Bowl",
    cloudinaryImageId: "6e04be27387483a7c00444f8e8241108",
    locality: "Lakshminarayana Pura",
    areaName: "Chinnapanna Halli",
    costForTwo: "₹400 for two",
    cuisines: ["Biryani", "Pastas", "Punjabi", "Desserts", "Beverages"],
    avgRating: 4.3,
    parentId: "7918",
    avgRatingString: "4.3",
    totalRatingsString: "1K+",
    sla: {
      deliveryTime: 22,
      lastMileTravel: 1.8,
      serviceability: "SERVICEABLE",
      slaString: "22 mins",
      lastMileTravelString: "1.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "18772",
    name: "California Burrito",
    cloudinaryImageId: "zwwvf8n0jlo1bjx19qzg",
    locality: "Marathahalli",
    areaName: "Marathahalli",
    costForTwo: "₹250 for two",
    cuisines: [
      "Mexican",
      "American",
      "Salads",
      "Continental",
      "Keto",
      "Healthy Food",
    ],
    avgRating: 4.5,
    parentId: "1252",
    avgRatingString: "4.5",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 22,
      lastMileTravel: 4.5,
      serviceability: "SERVICEABLE",
      slaString: "22 mins",
      lastMileTravelString: "4.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "86516",
    name: "Daily Sushi",
    cloudinaryImageId: "kledz86hpq4prx7gzjat",
    locality: "Varthur Road",
    areaName: "Whitefield",
    costForTwo: "₹1200 for two",
    cuisines: ["Japanese", "Asian", "Korean"],
    avgRating: 4.3,
    parentId: "7388",
    avgRatingString: "4.3",
    totalRatingsString: "1K+",
    sla: {
      deliveryTime: 28,
      lastMileTravel: 2.5,
      serviceability: "SERVICEABLE",
      slaString: "28 mins",
      lastMileTravelString: "2.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "457821",
    name: "Istah - The Mediterranean Way",
    cloudinaryImageId: "67d4a416bf932f850b0a15ad33aae762",
    locality: "Munnekolala",
    areaName: "Marathahalli",
    costForTwo: "₹250 for two",
    cuisines: [
      "Mediterranean",
      "Snacks",
      "Biryani",
      "Grill",
      "Kebabs",
      "Arabian",
      "Lebanese",
      "Beverages",
      "Desserts",
      "Italian",
      "Turkish",
    ],
    avgRating: 4.4,
    parentId: "3518",
    avgRatingString: "2.4",
    totalRatingsString: "5K+",
    sla: {
      deliveryTime: 23,
      lastMileTravel: 3,
      serviceability: "SERVICEABLE",
      slaString: "23 mins",
      lastMileTravelString: "3.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "234631",
    name: "Truffles",
    cloudinaryImageId: "cd832b6167eb9f88aeb1ccdebf38d942",
    locality: "Kaveri Nagar",
    areaName: "Garudacharpalya",
    costForTwo: "₹350 for two",
    cuisines: [
      "American",
      "Continental",
      "Desserts",
      "Bakery",
      "Beverages",
      "Pastas",
      "Italian",
    ],
    avgRating: 4.5,
    parentId: "218065",
    avgRatingString: "4.5",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 29,
      lastMileTravel: 7.3,
      serviceability: "SERVICEABLE",
      slaString: "29 mins",
      lastMileTravelString: "7.3 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "18976",
    name: "Nandhana Palace",
    cloudinaryImageId: "195876a3181ef63f76e45e3a7b49b585",
    locality: "Marathahalli",
    areaName: "Marathahalli",
    costForTwo: "₹500 for two",
    cuisines: ["Biryani", "Andhra", "South Indian", "North Indian"],
    avgRating: 4.2,
    parentId: "2120",
    avgRatingString: "4.2",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 25,
      lastMileTravel: 5.5,
      serviceability: "SERVICEABLE",
      slaString: "25 mins",
      lastMileTravelString: "5.5 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "35857",
    name: "Sweet Truth - Cake and Desserts",
    cloudinaryImageId: "81cf6bfe2760a45a0caf2e28716ca4d7",
    locality: "Lakshminarayana Pura",
    areaName: "Chinnapanna Halli",
    costForTwo: "₹450 for two",
    cuisines: ["Snacks", "Bakery", "Desserts", "Beverages"],
    avgRating: 3,
    parentId: "4444",
    avgRatingString: "3.0",
    totalRatingsString: "1K+",
    sla: {
      deliveryTime: 22,
      lastMileTravel: 1.8,
      serviceability: "SERVICEABLE",
      slaString: "22 mins",
      lastMileTravelString: "1.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "349072",
    name: "Baskin Robbins - Ice Cream Desserts",
    cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
    locality: "Kundanahalli, Brookefield",
    areaName: "Marathahalli",
    costForTwo: "₹250 for two",
    cuisines: ["Desserts", "Ice Cream"],
    avgRating: 4.6,
    veg: true,
    parentId: "5588",
    avgRatingString: "4.6",
    totalRatingsString: "1K+",
    sla: {
      deliveryTime: 21,
      lastMileTravel: 2.8,
      serviceability: "SERVICEABLE",
      slaString: "21 mins",
      lastMileTravelString: "2.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "214427",
    name: "CakeZone",
    cloudinaryImageId: "e386a679bad57c2527925e5a22cd283a",
    locality: "SRI VINAYAKA TECH PARK",
    areaName: "Mahadevapura",
    costForTwo: "₹200 for two",
    cuisines: ["Bakery", "Desserts", "Sweets", "Ice Cream"],
    avgRating: 3.5,
    parentId: "7003",
    avgRatingString: "3.5",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 28,
      lastMileTravel: 5.9,
      serviceability: "SERVICEABLE",
      slaString: "28 mins",
      lastMileTravelString: "5.9 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
];

export default resArray;
